[project]
name = "vlm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "looptick==0.1.2",
    "openai>=1.107.1",
    "opencv-python>=4.12.0.88",
    "pip>=25.2",
    "rich>=14.1.0",
    "zai-sdk>=0.0.3.5",
]
